import UserList from "./elements/UserList.js";
import UserListItem from "./elements/UserListItem.js";
import Album from "./elements/Album.js";
import AlbumList from "./elements/AlbumList.js";
import AlbumListItem from "./elements/AlbumListItem.js";
import Photo from "./elements/Photo.js";
import PhotoPreview from "./elements/PhotoPreview.js";
import FavoritePhotos from "./elements/FavoritePhotos.js";
import Tabs from "./elements/Tabs.js";
import TabsContent from "./elements/TabsContent.js";
import Preloader from "./elements/Preloader.js";
import Error from "./elements/Error.js";
customElements.define("error-element", Error);
customElements.define("preloader-element", Preloader);
customElements.define("tabs-navigation", Tabs);
customElements.define("tabs-content", TabsContent);
customElements.define("user-list-item", UserListItem);
customElements.define("user-list", UserList);
customElements.define("album-photo", Photo);
customElements.define("photo-preview", PhotoPreview);
customElements.define("favorite-photos", FavoritePhotos);
customElements.define("user-album", Album);
customElements.define("album-list", AlbumList);
customElements.define("album-list-item", AlbumListItem);
